const ROLES = {
  USER: 'USER',
  LMO: 'LMO',
  GATC: 'GATC',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

const APPLICATION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ASSIGNED: 'ASSIGNED',
  SCHEDULED: 'SCHEDULED',
  INSPECTION_IN_PROGRESS: 'INSPECTION_IN_PROGRESS',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CERTIFICATE_GENERATED: 'CERTIFICATE_GENERATED',
  EXPIRED: 'EXPIRED',
  REVERIFICATION_REQUIRED: 'REVERIFICATION_REQUIRED'
};

const APPLICATION_TYPES = {
  NEW_VERIFICATION: 'NEW_VERIFICATION',
  RE_VERIFICATION: 'RE_VERIFICATION',
  RENEWAL: 'RENEWAL'
};

const INSTRUMENT_STATUS = {
  REGISTERED: 'REGISTERED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  EXPIRED: 'EXPIRED',
  REJECTED: 'REJECTED'
};

const CERTIFICATE_STATUS = {
  VALID: 'VALID',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
};

const NOTIFICATION_TYPES = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ALERT: 'ALERT'
};

module.exports = {
  ROLES,
  APPLICATION_STATUS,
  APPLICATION_TYPES,
  INSTRUMENT_STATUS,
  CERTIFICATE_STATUS,
  NOTIFICATION_TYPES
};
